version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/easy-task-backend:latest
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: easy_task
      DB_PORT: 3306
    networks:
      - app-network

  frontend:
    image: ${DOCKERHUB_USERNAME}/easy-task-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "4200:80"
    environment:
      - VITE_API_URL=${API_URL}
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge