#Docker mysql-db container connect
#spring.datasource.url=jdbc:mysql://mysql-db:3306/easy_task?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

#Localhost mysql connect
#spring.datasource.url=jdbc:mysql://localhost:3306/easy_task
#spring.application.name=backend
#spring.datasource.password=1234
#spring.datasource.username=root

spring.datasource.url=${DB_URL}
spring.application.name=backend
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
API_URL=${API_URL}